# Ruta de la Wallet en la computadora local
oracle.net.wallet_location=(SOURCE=(METHOD=file)(METHOD_DATA=(DIRECTORY=C:/PROYECTOS/AWGVA_integradora/src/main/resources/Wallet)))
oracle.net.tns_admin=C:/PROYECTOS/AWGVA_integradora/src/main/resources/Wallet

# Configuraciones SSL / JKS para Oracle Cloud
javax.net.ssl.trustStore=C:/PROYECTOS/AWGVA_integradora/src/main/resources/Wallet/truststore.jks
javax.net.ssl.trustStoreType=JKS
javax.net.ssl.trustStorePassword=AWGVAint3Bdsm

javax.net.ssl.keyStore=C:/PROYECTOS/AWGVA_integradora/src/main/resources/Wallet/keystore.jks
javax.net.ssl.keyStoreType=JKS
javax.net.ssl.keyStorePassword=AWGVAint3Bdsm