# Connection property while using Oracle wallets.
# (Comentado para desactivar el modo SSO que causa el error)
# oracle.net.wallet_location=(SOURCE=(METHOD=FILE)(METHOD_DATA=(DIRECTORY=${TNS_ADMIN})))

# Configuraciones activadas para usar el formato JKS compatible con Tomcat
javax.net.ssl.trustStore=${TNS_ADMIN}/truststore.jks
javax.net.ssl.trustStoreType=JKS
javax.net.ssl.trustStorePassword=AWGVAint3Bdsm

javax.net.ssl.keyStore=${TNS_ADMIN}/keystore.jks
javax.net.ssl.keyStoreType=JKS
javax.net.ssl.keyStorePassword=AWGVAint3Bdsm